### ISSUE TITLE
会直接崩溃，希望修改

### ISSUE THREAD

**Issue by ankhze** [nenseso/NenPingManager#1]
有时候会直接崩溃
<img width="1053" alt="WeChat68203210fb4f52dcc929170d06248060" src="https://user-images.githubusercontent.com/49584570/61689805-7dc16900-ad5a-11e9-9ddf-b9674a46a64a.png">
<img width="1023" alt="WeChat6c0803a529cad13965045178767c227b" src="https://user-images.githubusercontent.com/49584570/61689826-8619a400-ad5a-11e9-8f50-ff80fa2f8a73.png">

**Comment by nenseso** [comment]
检查发现是包发送失败的时候会清空整个数组，但是有的包返回成功又会重新去访问数组导致的越界错误。
现在修复为当是包发送错误的时候,只清除对应的发送数据,为了保证不再越界错误，特别加了一个数据校验
